// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFGbnnOzS16gQtH7Atf2SAw5dZPteyTMg',
    appId: '1:290710242724:web:56038fab10e109f6e2ad31',
    messagingSenderId: '290710242724',
    projectId: 'cr-aprende-demo',
    authDomain: 'cr-aprende-demo.firebaseapp.com',
    storageBucket: 'cr-aprende-demo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvA8IaBljrfiT-n2wcTm5joVZM-0jN5co',
    appId: '1:290710242724:android:582182739ca85d7de2ad31',
    messagingSenderId: '290710242724',
    projectId: 'cr-aprende-demo',
    storageBucket: 'cr-aprende-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeQIS3oh_AEb7YDmj7NhejHH2WnhmF5L0',
    appId: '1:290710242724:ios:8d14ec5af261f3e5e2ad31',
    messagingSenderId: '290710242724',
    projectId: 'cr-aprende-demo',
    storageBucket: 'cr-aprende-demo.appspot.com',
    iosClientId: '290710242724-pr0im383cjkdq92qnrnfvh7h9gqrfoq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.unitConverter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeQIS3oh_AEb7YDmj7NhejHH2WnhmF5L0',
    appId: '1:290710242724:ios:8d14ec5af261f3e5e2ad31',
    messagingSenderId: '290710242724',
    projectId: 'cr-aprende-demo',
    storageBucket: 'cr-aprende-demo.appspot.com',
    iosClientId: '290710242724-pr0im383cjkdq92qnrnfvh7h9gqrfoq8.apps.googleusercontent.com',
    iosBundleId: 'com.example.unitConverter',
  );
}
